apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ui4myy41d-nodejs 
  janus-idp.io/tekton: ui4myy41d-nodejs
  backstage.io/kubernetes-id: ui4myy41d-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ui4myy41d-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml