apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ui4myy41d-nodejs
  janus-idp.io/tekton: ui4myy41d-nodejs
  backstage.io/kubernetes-id: ui4myy41d-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ui4myy41d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
